### ISSUE TITLE
Infrared sensor: `blocking=False` does not appear to work

### ISSUE THREAD

**Issue by timvandermeij** [timvandermeij/drone-tomography#54]
The `python-lirc` library is supposed to have a fix for this, but it appears that calls to `lirc.nextcode()` are still blocking. We might need to convert the code to use the `pylirc` library instead.

**Comment by lhelwerd** [comment]
`pylirc` does not seem to be maintained (the last version, 0.0.5, is from 2005) and while there is a [package page](https://pypi.python.org/pypi/pylirc), `pip` will not download from it since it knows no source location. The library can be found on [SourceForge](https://sourceforge.net/projects/pylirc/) though... Looking at the code, I see no major differences that would cause it to support non-blocking mode better than `python-lirc` does. I am not sure if this is anything that can be fixed; `lirc.nextcode()` seems to block irrespective from whether the internal socket blocks or not.

**Comment by timvandermeij** [comment]
Fixed by switching to the `pylirc2` library.
