### ISSUE TITLE
Replace valid fields in XBee packets with invalid location

### ISSUE THREAD

**Issue by timvandermeij** [timvandermeij/drone-tomography#63]
This is just an idea I got after reviewing the valid location PR, but could we perhaps simplify the valid location handling by not putting booleans in the packets, but instead put only valid locations (for instance, nonzero) the packets and zero locations otherwise? So, instead of the `valid` field, we provide either a valid location or 0. The receiver will treat 0 as an invalid location and everything else as a valid location.

**Comment by lhelwerd** [comment]
We decided not to do this since the location can be anything. In fact for the robot vehicle it starts with a local location of `(0,0)`. Negative coordinates are possible with GPS. Although infinity is an invalid location and can be packed into the XBee packet, it becomes cumbersome to check for this when we already have the boolean flag.
